defaults:
  - _self_
  - task: pt
  - local_env: default

# Experiment args
mode: 'pt'
device: gpu
precision: 'bf16'
eval_only: false
predict_only: false
seed: 2137

model:
  klass: local_t5
  name: 'google/t5-v1_1-base'
  overwrite: # overwrite config with these values
    dropout_rate: 0.0
    feed_forward_proj: "gated-silu"
    dense_act_fn: "silu"
  add_config: # add these values to the config
    is_bf16: false
  checkpoint_path: ''
  random_init: true
  compile: true # Pytorch 2.0

data:
  input_length: 1024
  mlm_probability: 0.15
  mean_noise_span_length: 3.0
  num_workers: 8
  # data_collator: ""
  data_collator: ul2
  data_collator_args:
    max_token_length: 1024

optim:
  name: adamwscale
  base_lr: 2e-2
  batch_size: 4
  total_steps: 65536
  epochs: -1 # If it's > 0 it overwrites total_steps
  warmup_steps: 1000
  lr_scheduler: cosine
  weight_decay: 0.001
  grad_clip: 1.0
  grad_acc: 128
  final_cosine: 1e-5

eval:
  every_steps: 100000 # Eval once in the end
  steps: 500

checkpoint:
  every_steps: 1000 # Save checkpoint once in the end

logging:
  every_steps: 10
  grad_l2: true
  weights_l2: true
  use_wandb: true
  # Remove or comment out the wandb_config section if not using Weights & Biases
  wandb_config:
    project: nanoT5
    entity: amazingvince
    tags: ["tag1", "tag2"]
    mode: "online"

hydra:
  job:
    chdir: True
